name: CI/CD for .NET App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        login-server: container66.azurecr.io

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: container66.azurecr.io/projedotv2:latest

    - name: Build with Oryx (if needed for platform detection)
      run: |
        curl -sSL https://aka.ms/install-dotnet.sh | bash /dev/stdin --version 9.0

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: finaldotproje
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
        platform: "dotnet"   
